### ISSUE TITLE
Create a to-do example app

### ISSUE THREAD

**Issue by golota60** [golota60/oxytail#8]
We need more demos, to see what are the shortcomings, and what nice-to-haves we can provide. This task is not tracking just creating the example, but also reporting additional issues encountered while creating it.

**Comment by spacedevin** [comment]
Comparing this to running floem on macos:

Examples & floem features to add to add
- [ ] placeholder text
- [ ] slider
- [ ] dropdown
- [ ] button click transitions
- [ ] checkbox click transitions
- [ ] radio click transitions
- [ ] ~~button hover transitions~~ seems to have fixed itself at times
- [ ] checkbox hover transitions
- [ ] radio hover transitions
- [ ] lists

Issues:
- [ ] Selecting text in an input wont select when the cursor is over the text. only when cursor is above or below. Both functionally and visibly.


it would be helpful to keep somewhat parity between this and floem to confirm regression
